/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.mainViews;

import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 * 
 * @author Parley
 */
public abstract class ClienteView extends JDialog {

    /**
     * Creates new form ClienteView
     */
    public ClienteView(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public abstract Iterator getIterator();

    public abstract void cadastrarAction();

    public abstract void alterarAction(int index);

    public abstract void excluirAction();

    protected Vector<String> fillDataVector(Cliente cliente) {

        Vector<String> nomesTabela = new Vector<String>();

        if (cliente == null) {
            return null;
        }

        nomesTabela.add(cliente.getMatricula());
        nomesTabela.add(cliente.getNome());
        nomesTabela.add(cliente.getTelefone());
        nomesTabela.add(cliente.getCpf());
        nomesTabela.add(cliente.getEmail());

        return nomesTabela;

    }

    protected DefaultTableModel fillTable() {
        DefaultTableModel table = new DefaultTableModel();

        Iterator<Cliente> i = getIterator();

        table.addColumn("Matricula");
        table.addColumn("Nome");
        table.addColumn("Telefone");
        table.addColumn("CPF");
        table.addColumn("E-mail");

        while (i.hasNext()) {
            // int col, row = 0;
            Cliente cliente = i.next();
            table.addRow(fillDataVector(cliente));
        }

        return table;
    }

    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotoes = new JPanel();
        cadastrarBtn = new JButton();
        alterarBtn = new JButton();
        excluirBtn = new JButton();
        panelLista = new JPanel();
        pesquisarLbl = new JLabel();
        pesquisarTextField = new JTextField();
        jScrollPane1 = new JScrollPane();
        tabelaCliente = new JTable();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");

        panelBotoes.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));

        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.setName("Cadastrar");
        cadastrarBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        alterarBtn.setText("Alterar");
        alterarBtn.setName("Alterar");
        alterarBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                alterarBtnActionPerformed(evt);
            }
        });

        excluirBtn.setText("Excluir");
        excluirBtn.setName("Excluir");
        excluirBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                excluirBtnActionPerformed(evt);
            }
        });

        GroupLayout panelBotoesLayout = new GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(panelBotoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                        panelBotoesLayout
                                .createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        panelBotoesLayout
                                                .createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(excluirBtn, GroupLayout.DEFAULT_SIZE,
                                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(alterarBtn, GroupLayout.DEFAULT_SIZE,
                                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cadastrarBtn, GroupLayout.DEFAULT_SIZE, 135,
                                                        Short.MAX_VALUE)).addContainerGap()));
        panelBotoesLayout.setVerticalGroup(panelBotoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                        panelBotoesLayout
                                .createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(cadastrarBtn, GroupLayout.PREFERRED_SIZE, 80,
                                        GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alterarBtn, GroupLayout.PREFERRED_SIZE, 82,
                                        GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(excluirBtn, GroupLayout.PREFERRED_SIZE, 80,
                                        GroupLayout.PREFERRED_SIZE).addContainerGap(78, Short.MAX_VALUE)));

        pesquisarLbl.setText("Digite a matricula desejada: ");

        pesquisarTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pesquisarTextFieldActionPerformed(evt);
            }
        });

        GroupLayout panelListaLayout = new GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(panelListaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                        panelListaLayout.createSequentialGroup().addContainerGap().addComponent(pesquisarLbl)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesquisarTextField)));
        panelListaLayout.setVerticalGroup(panelListaLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
                panelListaLayout
                        .createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                                panelListaLayout
                                        .createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(pesquisarLbl, GroupLayout.PREFERRED_SIZE, 28,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pesquisarTextField, GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        tabelaCliente.setModel(fillTable());
        tabelaCliente.setName("tabelaCliente");
        jScrollPane1.setViewportView(tabelaCliente);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
                GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(panelLista, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBotoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(
                                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(
                                                layout.createSequentialGroup()
                                                        .addComponent(panelLista, GroupLayout.DEFAULT_SIZE,
                                                                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 353,
                                                                GroupLayout.PREFERRED_SIZE))
                                        .addComponent(panelBotoes, GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarTextFieldActionPerformed(ActionEvent evt) {// GEN-FIRST:event_pesquisarTextFieldActionPerformed
        String nome = this.pesquisarTextField.getText();
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum texto digitado", "Erro", JOptionPane.ERROR_MESSAGE, null);
        } else {
            JOptionPane.showMessageDialog(this, "Funciona", "Teste", JOptionPane.WARNING_MESSAGE, null);
        }
    }// GEN-LAST:event_pesquisarTextFieldActionPerformed

    private void cadastrarBtnActionPerformed(ActionEvent evt) {// GEN-FIRST:event_cadastrarBtnActionPerformed
        // TODO add your handling code here:
        cadastrarAction();

    }// GEN-LAST:event_cadastrarBtnActionPerformed

    private void alterarBtnActionPerformed(ActionEvent evt) {// GEN-FIRST:event_alterarBtnActionPerformed
        // TODO add your handling code here:

        int index = this.tabelaCliente.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha!", "Erro", JOptionPane.ERROR_MESSAGE, null);
            return;
        }

        alterarAction(index);

    }// GEN-LAST:event_alterarBtnActionPerformed

    private void excluirBtnActionPerformed(ActionEvent evt) {// GEN-FIRST:event_excluirBtnActionPerformed
        excluirAction();

    }// GEN-LAST:event_excluirBtnActionPerformed
     // Variables declaration - do not modify//GEN-BEGIN:variables

    private JButton alterarBtn;
    private JButton cadastrarBtn;
    private JButton excluirBtn;
    private JScrollPane jScrollPane1;
    private JPanel panelBotoes;
    private JPanel panelLista;
    private JLabel pesquisarLbl;
    private JTextField pesquisarTextField;
    protected JTable tabelaCliente;
    // End of variables declaration//GEN-END:variables
}
